version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: carbon_footprint
    restart: always
    environment:
      POSTGRES_DB: carbon_footprint
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432